Repository tinkerbell/playground, pull requests merged in 2021-03, with the labels that each got.

#57 Fix port collision between boots and nginx
  deploy/docker-compose.yml
Labels: ci-check/vagrant-setup, ready-to-merge

#61 add current_versions.sh file to the terraform provisioner
  deploy/terraform/main.tf
Labels: ready-to-merge

#63 remove the metadata filter in the sandbox
  deploy/docker-compose.yml
Labels: ready-to-merge

#67 Rename _vagrant to vagrant
  .github/workflows/vagrant-packet.yaml
  go.mod
  go.sum
  shell.nix
  test/vagrant/vagrant_test.go
Labels: ci-check/vagrant-setup

#65 Add support for a nat-less libvirt deployment and multiple workers
  deploy/vagrant/Vagrantfile
  deploy/vagrant/scripts/tinkerbell.sh
Labels: ci-check/vagrant-setup, ready-to-merge

#68 pin boots to TINKERBELL_HOST_IP instead of 0.0.0.0
  deploy/docker-compose.yml
Labels: ci-check/vagrant-setup

#66 Bump tink stack to newest version
  current_versions.sh
Labels: ci-check/vagrant-setup, ready-to-merge

#69 Revert osie because the latest version broke tink-worker installation
  current_versions.sh
Labels: ci-check/vagrant-setup, ready-to-merge

#70 Install btrfs devel
  .github/workflows/tags.yaml
Labels: ready-to-merge

#72 Update Terraform to 0.14 in shell.nix
  shell.nix
Labels: ready-to-merge
