Repository tinkerbell/playground, pull requests merged in 2021-01, with the labels that each got.

#32 Making statement on breaking changes clearer
  README.md
Labels: ready-to-merge

#33 provisioner setup changes to enable NAT for workers
  setup.sh
Labels: ci-check/vagrant-setup, ready-to-merge

#34 Bump tink stack 2021 01 11
  current_versions.sh
Labels: ci-check/vagrant-setup

#38 getbinariesfromquay: Remove - separating arch from variant
  cmd/getbinariesfromquay/main.go
Labels: bc-break, ready-to-merge

#39 Update boots
  current_versions.sh
Labels: ci-check/vagrant-setup, ready-to-merge

#41 Fix NAT and make it working for Terraform and Vagrant
  deploy/terraform/main.tf
  deploy/vagrant/scripts/tinkerbell.sh
  setup.sh
Labels: ready-to-merge

#44 Fix shfmt for tinkerbell.sh file
  deploy/vagrant/scripts/tinkerbell.sh
Labels: ready-to-merge

#42 Fix vagrant config for libvirt
  deploy/vagrant/Vagrantfile
Labels: ready-to-merge

#43 Use same IP address for both boots and nginx
  deploy/docker-compose.yml
  generate-envrc.sh
  setup.sh
Labels: bc-break, ci-check/vagrant-setup, ready-to-merge
